### PR TITLE
feature: Support a quipucords-app front-end

### PR DESCRIPTION
**Pull request by abellotti**
- Add support for a quipucords-app front-end (port 9443) which is not the only published port to the user. Accessing it as a gateway to the API's (discovery-server), V1 UI (discovery-server) or the V2 UI (discovery-app using the quipucords-ui-container)
- Support user specified application certs, via the .local/share/discovery/certs/ folder.
- Enable Celery by default for quadlet deployment.

Related PRs:
- https://github.com/quipucords/quipucords-ui/pull/344
- https://gitlab.cee.redhat.com/discovery/unofficial-internal-documentation/-/blob/main/how-to-guides/Deployments/Quadlet.md?ref_type=heads

### CODE REVIEW

**Comment by abellotti** [comment]
With this enhanced Discovery quadlet deployment, the ui container now servers the user-facing `discovery-app` quadlet which exposes the 9443 port. Here are the running quadlets:

image

And the default behavior gives us the v1 UI of Discovery:

image

**Comment by abellotti** [comment]
To change behavior to show the V2 UI in development,  update the `QUIPUCORDS_APP_ENABLE_V2UI` value to 1 in the ~/.config/discovery/env/env-app.env file:

```
QUIPUCORDS_APP_PORT=9443
QUIPUCORDS_APP_ENABLE_V2UI=1
QUIPUCORDS_SERVER_URL=https://discovery-server:8443
```

And restart the front-end:

```
$ systemctl --user restart discovery-app
```

Hitting the 9443 endpoint now gives us:

image

**Comment by abellotti** [comment]
With this PR, the `discovery-app` nginx /var/log/nginx get saved in the log shared volume as shown here:

```
$ ls -FC $HOME/.local/share/discovery/log
app.log                          scan-job-138-ansible-stderr.txt  scan-job-34-ansible-stdout.txt
celery_worker.log                scan-job-138-ansible-stdout.txt  scan-job-3-ansible-stderr.txt
nginx/                           scan-job-139-ansible-stderr.txt  scan-job-3-ansible-stdout.txt
scan-job-103-ansible-stderr.txt  scan-job-139-ansible-stdout.txt  scan-job-69-ansible-stderr.txt
...
```

```
$ ls -la $HOME/.local/share/discovery/log/nginx
total 40
drwxr-xr-x. 2 abellotti    100000    41 Apr 24 20:15 .
drwxrwxrwx. 3 abellotti abellotti  4096 Apr 24 20:15 ..
-rw-r--r--. 1 abellotti    100000 30176 Apr 25 05:15 access.log
-rw-r--r--. 1 abellotti    100000  2551 Apr 25 05:11 error.log
```

There is also a new shared volume `$HOME/.local/share/discovery/certs` that gets mounted to the quadlet's `/opt/app-root/certs/` directory. This is where the self-signed certificate for the discovery app gets created or where the customer provides their server certificate to use with the discovery app.

```
$ ls -la $HOME/.local/share/discovery/certs
total 8
drwxr-xr-x. 2 abellotti abellotti   42 Apr 25 05:42 .
drwxr-xr-x. 7 abellotti abellotti   78 Apr 25 05:42 ..
-rw-r--r--. 1 abellotti    100000 1444 Apr 25 05:11 server.crt
-rw-------. 1 abellotti    100000 1704 Apr 25 05:11 server.key
```

**Comment by abellotti** [comment]
With the added orchestration, discovery quadlets are started and stopped with `discovery-app` via dependency specifications.

Now, starting and stopping all of discovery is simply:

```
$ systemctl --user start discovery-app
```

and

```
$ systemctl --user stop discovery-app
```

image


```
abellotti $ list-dsc
  UNIT                      LOAD   ACTIVE SUB    DESCRIPTION              
  discovery-network.service loaded active exited discovery-network.service

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
1 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
aab-dsc:discovery/ (quadlet-deployment) python: 3.9.18
abellotti $ systemctl --user start discovery-app
aab-dsc:discovery/ (quadlet-deployment) python: 3.9.18
abellotti $ list-dsc
  UNIT                            LOAD   ACTIVE SUB     DESCRIPTION                      
  discovery-app.service           loaded active running Discovery App
  discovery-celery-worker.service loaded active running Discovery Celery Worker
  discovery-db.service            loaded active running PostgreSQL Database for Discovery
  discovery-network.service       loaded active exited  discovery-network.service
  discovery-redis.service         loaded active running Redis for Discovery
  discovery-server.service        loaded active running Discovery Server

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
6 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
aab-dsc:discovery/ (quadlet-deployment) python: 3.9.18
abellotti $ 
```

image

**Review by bruno-fs — APPROVED** [review]

**Pull request merged**
